# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_0/design_1_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_TDCChannelSlice_1_0/design_1_TDCChannelSlice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_TDCChannelSlice_1_0 || ORIG_REF_NAME==design_1_TDCChannelSlice_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_2_0/design_1_xlconstant_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_2_0 || ORIG_REF_NAME==design_1_xlconstant_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4Stream_XUS_Virtu_0_1/design_1_AXI4Stream_XUS_Virtu_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AXI4Stream_XUS_Virtu_0_1 || ORIG_REF_NAME==design_1_AXI4Stream_XUS_Virtu_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4Stream_IperDecod_0_1/design_1_AXI4Stream_IperDecod_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AXI4Stream_IperDecod_0_1 || ORIG_REF_NAME==design_1_AXI4Stream_IperDecod_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4Stream_CoarseExt_0_1/design_1_AXI4Stream_CoarseExt_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AXI4Stream_CoarseExt_0_1 || ORIG_REF_NAME==design_1_AXI4Stream_CoarseExt_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4Stream_MagicCali_0_1/design_1_AXI4Stream_MagicCali_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AXI4Stream_MagicCali_0_1 || ORIG_REF_NAME==design_1_AXI4Stream_MagicCali_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4Stream_OverflowC_0_1/design_1_AXI4Stream_OverflowC_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AXI4Stream_OverflowC_0_1 || ORIG_REF_NAME==design_1_AXI4Stream_OverflowC_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4Stream_Synchroni_0_1/design_1_AXI4Stream_Synchroni_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AXI4Stream_Synchroni_0_1 || ORIG_REF_NAME==design_1_AXI4Stream_Synchroni_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_BeltBus_NodeInserter_0_4/design_1_BeltBus_NodeInserter_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_BeltBus_NodeInserter_0_4 || ORIG_REF_NAME==design_1_BeltBus_NodeInserter_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_TDCChannelSlice_2_0/design_1_TDCChannelSlice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_TDCChannelSlice_2_0 || ORIG_REF_NAME==design_1_TDCChannelSlice_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_2_1/design_1_xlconstant_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_2_1 || ORIG_REF_NAME==design_1_xlconstant_2_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4Stream_XUS_Virtu_0_2/design_1_AXI4Stream_XUS_Virtu_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AXI4Stream_XUS_Virtu_0_2 || ORIG_REF_NAME==design_1_AXI4Stream_XUS_Virtu_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4Stream_IperDecod_0_2/design_1_AXI4Stream_IperDecod_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AXI4Stream_IperDecod_0_2 || ORIG_REF_NAME==design_1_AXI4Stream_IperDecod_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4Stream_CoarseExt_0_2/design_1_AXI4Stream_CoarseExt_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AXI4Stream_CoarseExt_0_2 || ORIG_REF_NAME==design_1_AXI4Stream_CoarseExt_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4Stream_MagicCali_0_2/design_1_AXI4Stream_MagicCali_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AXI4Stream_MagicCali_0_2 || ORIG_REF_NAME==design_1_AXI4Stream_MagicCali_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4Stream_OverflowC_0_2/design_1_AXI4Stream_OverflowC_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AXI4Stream_OverflowC_0_2 || ORIG_REF_NAME==design_1_AXI4Stream_OverflowC_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4Stream_Synchroni_0_2/design_1_AXI4Stream_Synchroni_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AXI4Stream_Synchroni_0_2 || ORIG_REF_NAME==design_1_AXI4Stream_Synchroni_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_BeltBus_NodeInserter_0_5/design_1_BeltBus_NodeInserter_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_BeltBus_NodeInserter_0_5 || ORIG_REF_NAME==design_1_BeltBus_NodeInserter_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4Stream_PeriodMet_0_0/design_1_AXI4Stream_PeriodMet_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AXI4Stream_PeriodMet_0_0 || ORIG_REF_NAME==design_1_AXI4Stream_PeriodMet_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_TDCChannelSlice_0_0/design_1_TDCChannelSlice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_TDCChannelSlice_0_0 || ORIG_REF_NAME==design_1_TDCChannelSlice_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_broadcaster_0_0/design_1_axis_broadcaster_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_broadcaster_0_0 || ORIG_REF_NAME==design_1_axis_broadcaster_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_0/design_1_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_0 || ORIG_REF_NAME==design_1_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4Stream_XUS_Virtu_0_0/design_1_AXI4Stream_XUS_Virtu_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AXI4Stream_XUS_Virtu_0_0 || ORIG_REF_NAME==design_1_AXI4Stream_XUS_Virtu_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4Stream_IperDecod_0_0/design_1_AXI4Stream_IperDecod_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AXI4Stream_IperDecod_0_0 || ORIG_REF_NAME==design_1_AXI4Stream_IperDecod_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4Stream_CoarseExt_0_0/design_1_AXI4Stream_CoarseExt_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AXI4Stream_CoarseExt_0_0 || ORIG_REF_NAME==design_1_AXI4Stream_CoarseExt_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4Stream_MagicCali_0_0/design_1_AXI4Stream_MagicCali_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AXI4Stream_MagicCali_0_0 || ORIG_REF_NAME==design_1_AXI4Stream_MagicCali_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4Stream_OverflowC_0_0/design_1_AXI4Stream_OverflowC_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AXI4Stream_OverflowC_0_0 || ORIG_REF_NAME==design_1_AXI4Stream_OverflowC_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4Stream_Synchroni_0_0/design_1_AXI4Stream_Synchroni_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AXI4Stream_Synchroni_0_0 || ORIG_REF_NAME==design_1_AXI4Stream_Synchroni_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_BeltBus_NodeInserter_0_3/design_1_BeltBus_NodeInserter_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_BeltBus_NodeInserter_0_3 || ORIG_REF_NAME==design_1_BeltBus_NodeInserter_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_CoarseTreeDistributor_0_0/design_1_CoarseTreeDistributor_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_CoarseTreeDistributor_0_0 || ORIG_REF_NAME==design_1_CoarseTreeDistributor_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_StartStopGenerator_0_0/design_1_StartStopGenerator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_StartStopGenerator_0_0 || ORIG_REF_NAME==design_1_StartStopGenerator_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_1/design_1_util_vector_logic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_1 || ORIG_REF_NAME==design_1_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_1_0/design_1_util_vector_logic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_0 || ORIG_REF_NAME==design_1_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_0/design_1_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_0 || ORIG_REF_NAME==design_1_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_0/design_1_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_0 || ORIG_REF_NAME==design_1_xlslice_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_1_0/design_1_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_1_0 || ORIG_REF_NAME==design_1_xlslice_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_2_0/design_1_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_2_0 || ORIG_REF_NAME==design_1_xlslice_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_3_0/design_1_xlslice_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_3_0 || ORIG_REF_NAME==design_1_xlslice_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_4_0/design_1_xlslice_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_4_0 || ORIG_REF_NAME==design_1_xlslice_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_5_0/design_1_xlslice_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_5_0 || ORIG_REF_NAME==design_1_xlslice_5_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4Stream_MuxDebugg_0_0/design_1_AXI4Stream_MuxDebugg_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AXI4Stream_MuxDebugg_0_0 || ORIG_REF_NAME==design_1_AXI4Stream_MuxDebugg_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4_TDC_Wrapper_0_0/design_1_AXI4_TDC_Wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AXI4_TDC_Wrapper_0_0 || ORIG_REF_NAME==design_1_AXI4_TDC_Wrapper_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_BeltBus_TDCCounter_0_0/design_1_BeltBus_TDCCounter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_BeltBus_TDCCounter_0_0 || ORIG_REF_NAME==design_1_BeltBus_TDCCounter_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_BeltBus_TDCHistogrammer_0_0/design_1_BeltBus_TDCHistogrammer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_BeltBus_TDCHistogrammer_0_0 || ORIG_REF_NAME==design_1_BeltBus_TDCHistogrammer_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_BeltBus_TDCHistogrammer_1_0/design_1_BeltBus_TDCHistogrammer_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_BeltBus_TDCHistogrammer_1_0 || ORIG_REF_NAME==design_1_BeltBus_TDCHistogrammer_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_BeltBus_TTM_0_0/design_1_BeltBus_TTM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_BeltBus_TTM_0_0 || ORIG_REF_NAME==design_1_BeltBus_TTM_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_MME_0_0/design_1_MME_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_MME_0_0 || ORIG_REF_NAME==design_1_MME_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_2/design_1_xbar_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_2 || ORIG_REF_NAME==design_1_xbar_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_0/design_1_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_0 || ORIG_REF_NAME==design_1_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_broadcaster_0_1/design_1_axis_broadcaster_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_broadcaster_0_1 || ORIG_REF_NAME==design_1_axis_broadcaster_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_broadcaster_1_0/design_1_axis_broadcaster_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_broadcaster_1_0 || ORIG_REF_NAME==design_1_axis_broadcaster_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_3/design_1_xbar_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_3 || ORIG_REF_NAME==design_1_xbar_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_interconnect_0_0/design_1_axis_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_interconnect_0_0 || ORIG_REF_NAME==design_1_axis_interconnect_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_1/design_1_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_1 || ORIG_REF_NAME==design_1_xlconstant_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4Stream_UART_1_0/design_1_AXI4Stream_UART_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AXI4Stream_UART_1_0 || ORIG_REF_NAME==design_1_AXI4Stream_UART_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_1/design_1_clk_wiz_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_1 || ORIG_REF_NAME==design_1_clk_wiz_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_1_0 || ORIG_REF_NAME==design_1_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_1_1/design_1_xlconstant_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_1_1 || ORIG_REF_NAME==design_1_xlconstant_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_iic_0_0/design_1_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_iic_0_0 || ORIG_REF_NAME==design_1_axi_iic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4_AXIToIIC_0_0/design_1_AXI4_AXIToIIC_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AXI4_AXIToIIC_0_0 || ORIG_REF_NAME==design_1_AXI4_AXIToIIC_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_management_wiz_0_0/design_1_system_management_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_system_management_wiz_0_0 || ORIG_REF_NAME==design_1_system_management_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4Stream_QSPI_Prog_0_0/design_1_AXI4Stream_QSPI_Prog_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AXI4Stream_QSPI_Prog_0_0 || ORIG_REF_NAME==design_1_AXI4Stream_QSPI_Prog_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_quad_spi_0_0/design_1_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_quad_spi_0_0 || ORIG_REF_NAME==design_1_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4_BitstreamUpdater_0_0/design_1_AXI4_BitstreamUpdater_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AXI4_BitstreamUpdater_0_0 || ORIG_REF_NAME==design_1_AXI4_BitstreamUpdater_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_design_1_416M_0/design_1_rst_design_1_416M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_design_1_416M_0 || ORIG_REF_NAME==design_1_rst_design_1_416M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_0_0/design_1_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_system_ila_0_0 || ORIG_REF_NAME==design_1_system_ila_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_1 || ORIG_REF_NAME==design_1_auto_pc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_2/design_1_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_2 || ORIG_REF_NAME==design_1_auto_pc_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_3 || ORIG_REF_NAME==design_1_auto_pc_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s_arb_req_suppress_concat_0/design_1_s_arb_req_suppress_concat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_s_arb_req_suppress_concat_0 || ORIG_REF_NAME==design_1_s_arb_req_suppress_concat_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ss_slidr_0/design_1_auto_ss_slidr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_ss_slidr_0 || ORIG_REF_NAME==design_1_auto_ss_slidr_0} -quiet] -quiet

# XDC: /home/mconsonni/Desktop/Tesi/Projects/TDC_KCU105/TDC-KCU105.gen/sources_1/bd/design_1/design_1_ooc.xdc
